### ISSUE TITLE
Dynamic Explore Selection not working

### ISSUE THREAD

**Issue by njia123** [looker-open-source/looker-explore-assistant#112]
hello,
I have 2 explore_id in the explore_assistant_examples BQ table, but I am not seeing the exploreAI is able to "toggle" between the explore base on the question that the user has input? it's always using the 1st explore_id

**Comment by LukaFontanilla** [comment]
@njia123 that is correct and expected. The current behavior is that a user will select the explore they want to ask questions against, the model doesn't decide what explore to use based on the question. This is something we are evaluating however.
