### ISSUE TITLE
Deploying BQ Explore Assist to production

### ISSUE THREAD

**Issue by tkrywitsky-g** [looker-open-source/looker-explore-assistant#13]
Hello, 

I have followed the guide for the BigQuery deployment, including creating the BQ connection, LLM model, and dataset. I have also built the Looker extension using npm run build and uploaded the bundle.js file to my Looker instance.  

When I run the extension in Looker it hangs. When I look in the developer console as I first load the extension I see a 404 error from the Looker SDK. The URL is trying to connect to is: https://<my-looker-instance>.looker.app/api/internal/core/4.0/lookml_models/%3CThis%20is%20your%20Looker%20Model%20Name%3E/explores/%3CThis%20is%20your%20Looker%20Explore%20Name%3E?fields=fields

It appears that the LOOKER_EXPLORE and LOOKER_MODEL variables are not set. I set them locally when I ran the extension in my local VM, but it appears that when I package the application for upload to run in Looker itself that the variables are not set. 

Do I have to configure the LOOKER_MODEL, LOOKER_EXPLORE and BQML_MODEL_ID within Looker?

Thanks!

**Comment by LukaFontanilla** [comment]
Thanks for the context on the error itself! That's helpful. By setting them locally I presume you exported them in your bash shell or terminal? Can you try renaming the `.env_example` file to `.env`, removing the placeholders and filling in the variables there? Then rebuilding the bundle.js file and updating that in the Looker project?

I realize the documentation doesn't explicitly call out doing that (RE: `.env_example` -> `.env`).

**Comment by plc1220** [comment]
Hi @LukaFontanilla, 

I'm facing a similar issue. I'm not quite sure what to fill in for LOOKER_MODEL & LOOKER_EXPLORE.( I filled in an existing model and explore but don't seem to work, will try it again). I see your example stated "thelook" and "order_items" so I wonder if its referring to this? [ ](https://github.com/looker-open-source/thelook)
and [](https://github.com/looker-open-source/thelookevent/tree/master)
Is it using the big query public dataset "thelook_ecommerce"?

Thanks!

**Comment by Ryan-Gould-Google** [comment]
Hi @tkrywitsky-g, did this solve your issue? I am running into the same issue on one of my new instances.   Any guidance would be great thanks.
