### ISSUE TITLE
Dynamic Fields and Custom Measures

### ISSUE THREAD

**Issue by Abhilash42069** [looker-open-source/looker-explore-assistant#24]
Is there a way to add Custom Measures to the explore? Like if I want to show Average Sales by Month, how do I show it on the explore as a visualisation?

**Comment by LukaFontanilla** [comment]
This is something that we will be close to fully supporting in the next version release coming soon. As for now, you'll need to give the Explore Assistant example url's with sample custom dim/measure or table calc creations.
