### ISSUE TITLE
error: invalid path 'explore-assistant-api/thelook::order_items.jsonl

### ISSUE THREAD

**Issue by paweljabl** [looker-open-source/looker-explore-assistant#25]
hi,

trying to clone repo in Windows, getting the following error? 

$ git clone git@github.com:looker-open-source/looker-explore-assistant.git
Cloning into 'looker-explore-assistant'...
remote: Enumerating objects: 330, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (21/21), done.
Receiving oremote: Total 330 (delta 78), reused 72 (delta 72), pack-reused 237
Receiving objects: 100% (330/330), 645.30 KiB | 1.54 MiB/s, done.
Resolving deltas: 100% (187/187), done.
error: invalid path 'explore-assistant-api/thelook::order_items.jsonl'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would y consider renaming the file: "thelook::order_items.jsonl"; the error is likely due to the double colons (::).

**Comment by LukaFontanilla** [comment]
@paweljabl we've made an update to the repo that removes those files from the repo. The Cloud Function backend now just excepts a prompt (with the examples delivered in the prompt itself OR it can be modified to call to external resources: table, file system, etc. to fetch them).
