### ISSUE TITLE
Question regarding extension setup

### ISSUE THREAD

**Issue by venkatasangaraju** [looker-open-source/looker-explore-assistant#27]
Hi Team
I see we have to setup environment variables on the extension setup and we must specify model and explore names. That means we to create one extension per explore? Can we bundle the extension for all explores in the looker environment? TIA for your response.

Thanks 
VS

**Comment by LukaFontanilla** [comment]
As you had noted VS it is currently set up for one explore. But it can be configured for multiple or all explores on an instance (_we'd recommend hand selecting popular explores and loading example data for each of those as opposed to using all explores_). The Looker API has [this method](https://developers.looker.com/api/explorer/4.0/methods/LookmlModel/all_lookml_models) for fetching all explores & models. You would need to move the explore and model variables into state and load them all into a dropdown element for selection and if you'd like to stick to using Looker UI components [this dropdown component](https://looker-open-source.github.io/components/latest/?path=/docs/docs-fieldselect--docs) is a good one!
