### ISSUE TITLE
Cloud Function Development -appropriate environment variables

### ISSUE THREAD

**Issue by satonos** [looker-open-source/looker-explore-assistant#29]
Which files do I set these infomation?

`VERTEX_AI_ENDPOINT=<This is your Deployed Cloud Function Endpoint>
LOOKER_MODEL=<This is your Looker model name>
LOOKER_EXPLORE=<This is your Looker explore name>`

**Comment by LukaFontanilla** [comment]
In that version of the repo, Vertex AI Endpoint is only required for the Cloud Function deployment and it will be the url of the Cloud Function itself ie. the endpoint hit to reach Vertex.

Looker Model and Explore will be the name of the LookML model in your instance and the name of a given explore in that model you want to ask questions against.
