### ISSUE TITLE
NPM Run Start/Localhost:8080 Development Issue

### ISSUE THREAD

**Issue by ryan-gould-accenture** [looker-open-source/looker-explore-assistant#34]
Hi, thanks for the work on all of these.  I was successfully able to implement your other two extensions after a bit of troubleshooting.  Unfortunately, front-end webdev is one of my weaker skill sets and I'm hoping someone can help point me in the right direction.

I have completed backend set-up and working on the front end.  When I execute npm run start it appears as if the local server is running but upon navigating to https://localhost:8080/ all I see displayed is 
"Cannot GET /"

When I attempt to use the extension I also encounter runtime errors.  I have attached relevant screenshots.  Thanks.

![image](https://github.com/looker-open-source/looker-explore-assistant/assets/168147896/04d3f888-4d7c-4f8f-9417-2a46fe6d937c)
![image](https://github.com/looker-open-source/looker-explore-assistant/assets/168147896/82c18102-04aa-45d6-8e4a-d3ddb3d2e61e)

**Comment by ryan-gould-accenture** [comment]
Additionally, this is my .env file.  I have replaced the XXXX with my project name when attempting to deploy.
![image](https://github.com/looker-open-source/looker-explore-assistant/assets/168147896/91b029f8-118e-47d6-94d7-a2c101544a31)

**Comment by ryan-gould-accenture** [comment]
Updated PR and readmes helped solve issues.

**Comment by dmwelgus** [comment]
I am running into the same issue. Could you say which steps in particular helped resolve the problem?

**Comment by ManishKumarV** [comment]
+++1
