### ISSUE TITLE
Chat Page Infinite Load

### ISSUE THREAD

**Issue by ryan-gould-accenture** [looker-open-source/looker-explore-assistant#35]
Thanks to the updates in the latest PR I was able to implement the explore assistant but have not been able to unlock the chat functionality.  Upon clicking the chat button I see a spinning cirlce indicating loading but nothing ever refreshes and I am unable to find anything in the console logs to support this.  Thanks for any help you can provide.
![image](https://github.com/looker-open-source/looker-explore-assistant/assets/168147896/85be8ab3-0223-4c73-870e-36e06481a822)

**Comment by ryan-gould-accenture** [comment]
Resolved by loading refinement examples.  Though not explicitly listed, both the example prompts and refinement example tables must be loaded for the chat extension to work.

**Comment by venkatasangaraju** [comment]
Hi @ryan-gould-accenture do you have examples of how to load refinement examples table. i loaded the same way as example prompts but i get not valid json error while loading chat screen. TIA
