### ISSUE TITLE
context providing to promt

### ISSUE THREAD

**Issue by RishabhPandit-00** [looker-open-source/looker-explore-assistant#36]
Can you just point out what is the final prompt or content is going inside LLM in main branch ? because I see content going inside LLM is only user query(NLP) in main branch and that will not give us good inference.

**Comment by LukaFontanilla** [comment]
@RishabhPandit-00 I would recommend checking out [this video](https://youtu.be/fz5QOnx4a98?t=711) by an awesome partner of ours that does a deep dive on the Explore Assistant. They walk through all that is passed in the final prompt (which includes standard prompt instructions, training samples and the LookML Model metadata for an Explore as well as the question itself).
