### ISSUE TITLE
custom backend interaction from explore assistant frontend

### ISSUE THREAD

**Issue by amanpwl92** [looker-open-source/looker-explore-assistant#41]
right now , explore assistant frontend has capability to interact with vertex ai cloud function or big query backend. In some cases where organisations are having self hoisted looker and non GCP environment, they might need to interact with their custom backend deployed may be on AWS or on Prem etc.

**Comment by LukaFontanilla** [comment]
@amanpwl92, for the open source solution the integration examples we provide yes, are GCP based integration examples. However the components like the backend and where examples are fetched from are intended to be interchangeable with one's own infrastructure. For example, an AWS Lambda function that reaches to models on Sagemaker would expose an HTTPS endpoint just like the Cloud Function approach and could be substituted in as an environmental variable instead.
