### ISSUE TITLE
( Enhancement) Multiple Explore Ids available in the Assistant dropdown list 

### ISSUE THREAD

**Issue by pjabl** [looker-open-source/looker-explore-assistant#54]
explore-assistant-extension enhancement
This enhancement support a few features: 
- multiple explores from the dropdown 
- contextual history / samples 
- samples from BigQuery

Details:

1. BigQuery available explore_ids available in explore_assistant_examples should be automatically read (all) during application startup.
2. Extract distinct set of models from explore_ids. 
3. Use lookml_model api to fetch explores descriptions.
4. Make them available as the drop down list in the Assistant page , use Select looker component with descriptions.
5. Samples / History tabs should be contextual based on selected explore id.
6. Samples should be loaded from a new BigQuery table explore_assistant_samples, if BigQuery backend is deployed.

**Comment by LukaFontanilla** [comment]
https://github.com/looker-open-source/looker-explore-assistant/pull/75

**Comment by seuf** [comment]
Hello, I've deployed the latest version of looker explore assistant. Inserted multiple examples for different explores and I don"t see the explore select in the settings menu.
I think the latest commit https://github.com/looker-open-source/looker-explore-assistant/commit/090082c46c9aec79e066a05790ae1aba168f67ad  removed the behavior merged in #75 
Or should I do something else to enable the multi explore select ?
