### ISSUE TITLE
How to upload bundle.js.map

### ISSUE THREAD

**Issue by manmat** [looker-open-source/looker-explore-assistant#77]
The last step for setting up the UI is to upload the files from the generated `dist` directory. One of the files is `bundle.js.map`. When I upload this file Looker automatically adds `.lkml` extension and tells me that there are issues with the file.

**Comment by antfido** [comment]
hey, @manmat were you able to resolve it ?

**Comment by praveenkumar-bidgely** [comment]
@manmat You don't need to add this file. Ideally only bundle.js should suffice but I upload more than just that file. You can refer attached screenshot and upload the same. The application is working fine for us. 
To upload any file, just drag and drop into looker project...one file at a time. No need to change any extension. 
<img width="269" alt="Screenshot 2024-08-24 at 11 58 07 AM" src="https://github.com/user-attachments/assets/53d63b7c-1cc7-4f5b-ac98-2e5d3daa55bc">
