### ISSUE TITLE
Infinite loading on the initial "Hello" page without any error message

### ISSUE THREAD

**Issue by lucidhwee** [looker-open-source/looker-explore-assistant#84]
Hi team,
I'm having some trouble with the Looker Explore Assistant extension after deployment. When I access the extension, I'm getting an **infinite loading "Hello" page without any error message.** It happens both Looker Original and Looker Core of my testing environments.

In the past, I've been able to troubleshoot other issues by using the specific error messages that the Looker extension provides (e.g., "The error is likely related to your Look specific .env variables"). However, the current issue is more difficult to investigate because it doesn't provide any clues.

I would appreciate any suggestions you may have on how to investigate and troubleshoot this issue.

![image](https://github.com/user-attachments/assets/23e16a08-214c-4ef8-b670-181e04a03401)

**Comment by shubhampubmatic** [comment]
Facing similar issue.

We are in the process of setting up the latest version of Explore Assistant but are encountering this issue where the UI remains stuck on the loading screen with the message, "Hello. Getting everything ready...".
All network calls appear to be successful (returning 200 responses) and there are no pending network requests.
Additionally, there are no errors being displayed in the console.
I am attempting this setup using an admin account in Looker with full privileges.

**Comment by manhld0206** [comment]
I have managed to run it. We have to load samples data into BigQuery tables first in order for the extension to work.
You can check https://github.com/looker-open-source/looker-explore-assistant/blob/main/explore-assistant-examples/README.md

**Comment by ppinyapat111222** [comment]
@manhld0206  I load samples data into BigQuery just now following the link. It pop-up "Hello"  page for awhile and turn to white with no sample data showing in UI.
![Uploading Screenshot 2567-09-02 at 14.10.52.png…]()

**Comment by manhld0206** [comment]
@ppinyapat111222
From your description alone I couldn't guess the exact reason for the error yet.

Here are some notes which are not mentioned in the guide that helped me sucessfully deployed the extension
- If BigQuery backend is used, env variables regarding Cloud Function (`VERTEX_AI_ENDPOINT`, `VERTEX_CF_AUTH_TOKEN`) should be `None|null`. The reverse is also true I guess
- Data has to be inserted to all examples related BigQuery tables: `explore_assistant_examples`, `explore_assistant_refinement_examples ` and `explore_assistant_samples`
- Correct `explore_id` must be used in the above BigQuery tables. The format is `model:explore` and should reference actual Looker explore

Hope it could help you

**Comment by LukaFontanilla** [comment]
As @manhld0206 mentioned, ensure data is loaded into all 3 tables AND that all 3 tables have the same explore_id's  with the format ->`model_name:explore_name`. We progress pass the "Hello" page only when the data from those 3 tables are loaded. We can add improvements for handling when the required data is missing, null or undefined however.

**Comment by OgonnaO** [comment]
@LukaFontanilla Hello, I am having this same issue but I have uploaded the data to all 3 tables. The samples table kept erroring out, so I created 2 different models and 3 different explores for all 3 tables. All connected properly. I still have just the hello page loading forever. Please can you help?
